const Constants = {
  ROUTES: {
    LOGIN: "/",
    FORGOTPASSWORD: "/forgotpassword",
    RESET: "/reset",
    CREATE: "/create",
    DASHBOARD: "/dashboard",
    ONBOADING: "/onboarding",
    SETTING: "/setting",
    ACTIVATION: "/activation",
    PROFILE: "/profile",
    DIRECTORY: "/directory",
    EMPDASHBOARD: "/empdashboard",
    PAYSLIP:"/payslip"
  },
  LOADING: "please wait to load...",
  REMEMBER_ME_LABEL: "Remember me",
  FORGOT_PASSWORD_LABEL: "Forgot Password?",
  LOG_IN_LABEL: "Login",
  SUBMIT_BTN: "Submit",
  USERNAME_LABEL: "Username",
  EMAIL_PLACEHOLDER: "Please enter email",
  PASSWORD_LABEL: "Password",
  PASSWORD_PLACEHOLDER: "Please enter Password",
  LOGIN_SUBHEADING_LABEL1: "Welcome to",
  LOGIN_SUBHEADING_LABEL2: "PeopleCentral",
  PASSWORD: {
    NEW_PASSWORD: "New Password",
    OLD_PASSWORD: "Old Password",
    CONFIRM_PASSWORD: "Confirm Password",
  },
  CREATE_PASSWORD: "Create Password",
  CONFIRM_NEW_PASSWORD: "Confirm New Password",
  CREATE_PASSWORD_PLACEHOLDER: "Please Enter New password",
  CONFIRM_CREATE_PASSWORD_PLACEHOLDER: "Please Enter above password",
  SAVE_BTN: "Save Password",
  NEW_PASSWORD_PLACEHOLDER: "Please Enter your new password",
  CONFIRM_PASSWORD_PLACEHOLDER: "Please Enter above new password",
  SAVE_PASSWORD_BTN: "Save New Password",
};
export default Constants;